### ISSUE TITLE
Update the Calendar to use latest fullCalendar version

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/ee4-events-calendar#7]
## Issue Overview

From codebase https://events.codebasehq.com/projects/event-espresso/tickets/6245.
From @Pebblo:
> A custom is requesting a feature from within fullCalendar v2+
> (Here: http://eventespresso.com/topic/calendar-hours-show-in-week-and-day-vew/#post-106867)

Brent noted
>  I've already looked at FC 2.0 and it will require rewriting the EE Calendar JS

Full Calendar is on 3.9, but has a 4.0 in beta: https://github.com/fullcalendar/fullcalendar/releases

Upgrading our integration will probably add new features and possibly create some integration issues for existing users.

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by joshfeck** [comment]
We're not planning on doing this for the existing calendar add-on.
